# 毕设项目：驾驶员状态检测

使用深度学习方法检测驾驶员的状态。  

**输入：**一张彩色图片  
**输出：**十种状态的概率  

### 状态列表：  
* c0: 安全驾驶
* c1: 右手打字
* c2: 右手打电话
* c3: 左手打字
* c4: 左手打电话
* c5: 调收音机
* c6: 喝饮料
* c7: 拿后面的东西
* c8: 整理头发和化妆
* c9: 和其他乘客说话

### 可视化数据集
导入数据集，通过 matplotlib 来可视化我们的原始数据集。

In [24]:
import random
import numpy as np

>>> a = np.array((1,2,3))  
>>> b = np.array((2,3,4))  
>>> np.dstack((a,b))  
array([[[1, 2],  
        [2, 3],  
        [3, 4]]]) 

for i in range(10):
    b = [[i,i],[i,i]]
    a.append(b)
r = random.sample(a,5)
# print r
p = np.array([ [1,2,3] , [3,4,5] , [5,6,7]])
z = np.zeros((3, 1), dtype=p.dtype)
x = np.concatenate((p, z), axis=1)
print x
print x.shape

[[1 2 3 0]
 [3 4 5 0]
 [5 6 7 0]]
(3, 4)
